<a href="https://colab.research.google.com/github/half-anerd/Webscrapping-and-ML/blob/main/Kepler_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving kelperdata.csv to kelperdata.csv


In [2]:
import numpy as np
import pandas as pd

In [3]:
path ='/content/kelperdata.csv'
data = pd.read_csv(path, skiprows=52)

In [4]:
print(data.isnull().sum())

kepid                   0
kepoi_name              0
kepler_name          7204
koi_disposition         0
koi_pdisposition        0
koi_score            1510
koi_fpflag_nt           0
koi_fpflag_ss           0
koi_fpflag_co           0
koi_fpflag_ec           0
koi_period              0
koi_period_err1       454
koi_period_err2       454
koi_time0bk             0
koi_time0bk_err1      454
koi_time0bk_err2      454
koi_impact            363
koi_impact_err1       454
koi_impact_err2       454
koi_duration            0
koi_duration_err1     454
koi_duration_err2     454
koi_depth             363
koi_depth_err1        454
koi_depth_err2        454
koi_prad              363
koi_prad_err1         363
koi_prad_err2         363
koi_teq               363
koi_teq_err1         9564
koi_teq_err2         9564
koi_insol             321
koi_insol_err1        321
koi_insol_err2        321
koi_model_snr         363
koi_tce_plnt_num      346
koi_tce_delivname     346
koi_steff             363
koi_steff_er

In [5]:
codes = {'FALSE POSITIVE':0, 'CANDIDATE':1, 'CONFIRMED':2}
data['koi_disposition'] = data['koi_disposition'].map(codes)
data['koi_pdisposition'] = data['koi_pdisposition'].map(codes)

In [6]:
data.drop(['koi_teq_err1','koi_teq_err2'], axis=1, inplace=True)
data = data.select_dtypes(include=np.number)
data = data.dropna(axis=0)

In [7]:
y = data.iloc[:, 1]
X = data.drop(['koi_disposition'], axis = 1)

In [8]:
y.head()

0    2
1    2
2    1
3    0
4    2
Name: koi_disposition, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [11]:
param_grid = {
    'max_depth': [4, 5, 6, 7, 8, 9],
    'n_estimators': [50, 75, 100, 125, 150]
}

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

clf = RandomForestClassifier()

test_clf = GridSearchCV(clf, param_grid, cv=5)
test_clf.fit(X_train, y_train)

test_clf.best_params_

{'max_depth': 9, 'n_estimators': 125}

In [16]:
classifier = test_clf. best_estimator_

classifier.fit(X_train, y_train)
predictions = classifier.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[767   0   1]
 [  0 229  95]
 [  2  57 410]]
0.9007046764894299
